version: '3.7'

services:
  n8n-db:
    image: postgres:14
    container_name: n8n-db
    restart: always
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8npass
      POSTGRES_DB: n8n
    volumes:
      - n8n_postgres_data:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: n8n-db
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8npass

      N8N_HOST: n8n.lucianaferreira.pro
      N8N_PORT: 5678
      N8N_EDITOR_BASE_URL: http://n8n.lucianaferreira.pro
      WEBHOOK_URL: http://n8n.lucianaferreira.pro

      # ✅ Habilita autenticação persistente (sem desativar auth)
      N8N_USER_MANAGEMENT_DISABLED: false

      # ✅ Permite acesso à página /signup para novos usuários
      N8N_AUTH_EXCLUDE_ENDPOINTS: /signup

      # ✅ Suporte a nodes customizados
      N8N_CUSTOM_EXTENSIONS: /custom

    volumes:
      - ./custom_nodes:/custom
      - ~/.n8n:/home/node/.n8n
    depends_on:
      - n8n-db

volumes:
  n8n_postgres_data:

